# 5. Numpy and Linear Algebra

Numpy (Numerical Python) is the fundamental package for scientific computing in Python. It is a special library created for it, the core element is the multidimensional array object.

Numpy-s array class is called ndarray.

Numpy arrays have a fixed size at creation, unlike Python lists (changing the array will create a new one and delete the original).



In [6]:
import numpy as np

In [7]:
%%bash
which python

/home/dsc/anaconda3/bin/python


In [8]:
np.version.version

'1.15.4'

## Creating vectors and matrices (ndarrays)

Use the function np.array(), you can visualize the array this way:

![](https://fgnt.github.io/python_crashkurs_doc/_images/numpy_array_t.png)

In [9]:
list = [1, 2.0,3.1,4.2,-1,8.92]
a = np.array(list)
a.dtype

dtype('float64')

In [10]:
#dir(a)

In [11]:
a.shape

(6,)

In [12]:
a.ndim

1

In [13]:
a.dtype.name

'float64'

In [14]:
a.itemsize

8

In [15]:
a.size

6

In [16]:
type(a)

numpy.ndarray

In [18]:
np.array( [ [1,2], [3,4] ])

array([[1, 2],
       [3, 4]])

In [48]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [51]:
a


array([ 1.  ,  2.  ,  3.1 ,  4.2 , -1.  ,  8.92])

In [52]:
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
print(a.shape, a2.shape)
print(a.size,a2.size)

(6,) (4, 3)
6 12


In [44]:
np.ones(a2.shape)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.ones(a2.shape)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
a3 =  np.array([[1,2,3],[4,5,6]])
a3

array([[1, 2, 3],
       [4, 5, 6]])

Use `.tranpose()`

In [23]:
a3.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
print(np.zeros(10))
print(np.ones((2,3)))
#print np.ones_like(a2)
print(np.eye(4))
print(np.empty((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [25]:
np.arange(10000)

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [26]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ...,
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

In [27]:
np.random.random((2,3))

array([[0.77229743, 0.55853671, 0.52450336],
       [0.01543513, 0.18074962, 0.90637116]])

In [43]:
arr = np.array([1,4,2,1,3,6,6,9,4,2,4])
np.sort(arr)

array([1, 1, 2, 2, 3, 4, 4, 4, 6, 6, 9])

## Indexing, slicing and iterating


__Accessing narrays__

In [28]:
print(a)
print(a2)

[ 1.    2.    3.1   4.2  -1.    8.92]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [29]:
print(a[0],a2[0])

1.0 [1 2 3]


In [30]:
a2[1][0]

4

__Slicing__

In [31]:
a[1:3]

array([2. , 3.1])

In [32]:
a2[:]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
a2[:2,:2]

array([[1, 2],
       [4, 5]])

In [34]:
mybooleans = a2 >3
print(a2)
print(mybooleans)
a2[mybooleans].reshape((3,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[False False False]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [35]:
isthree= a2==3
isgtthree= a2>3
iseven= a2%2 ==0

In [36]:
print(a2[isthree])
print(a2[isgtthree])
print(a2[iseven])

[3]
[ 4  5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]


### Iterating

In [37]:
for row in a2:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


To perform an operation on each element in the array use `flat`

In [38]:
for element in a2.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12


## Copying

In [54]:
b=a2[1]
b

array([4, 5, 6])

In [55]:
b[1] = -1
b

array([ 4, -1,  6])

In [57]:
b[:]=3

In [58]:
a2

array([[ 1,  2,  3],
       [ 3,  3,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
c=a2[1].copy()
c

array([3, 3, 3])

In [44]:
c[:]=[1,-3,0]

In [45]:
print(c)
print(a2)

[ 1 -3  0]
[[ 1  2  3]
 [ 3  3  3]
 [ 7  8  9]
 [10 11 12]]


## Basic operations

In [46]:
print(a2)
a2*a2 

[[ 1  2  3]
 [ 3  3  3]
 [ 7  8  9]
 [10 11 12]]


array([[  1,   4,   9],
       [  9,   9,   9],
       [ 49,  64,  81],
       [100, 121, 144]])

In [47]:
a2 -a2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [48]:
1/a2

array([[1.        , 0.5       , 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.14285714, 0.125     , 0.11111111],
       [0.1       , 0.09090909, 0.08333333]])

In [49]:
np.sin(a2)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [ 0.14112001,  0.14112001,  0.14112001],
       [ 0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292]])

__On matrixes__

In [50]:
a

array([ 1.  ,  2.  ,  3.1 ,  4.2 , -1.  ,  8.92])

`np.dot(a,b)` This function returns the dot product of two arrays.

For 2-D vectors, it is the equivalent to matrix multiplication. 

For 1-D arrays, it is the inner product of the vectors. 

For N-dimensional arrays, it is a sum product over the last axis of a and the second-last axis of b


In [61]:
np.dot(a,a)

112.8164



If type(a) is not numpy.ndarray, then numpy.dot will convert a to an array and use the array for the multiplication, while `a.dot()` will do whatever a's type says it does, or raise an AttributeError if a doesn't have a dot method

In [59]:
a.dot(a)

112.8164

In [54]:
a2

array([[ 1,  2,  3],
       [ 3,  3,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [52]:
np.arange(3)

array([0, 1, 2])

In [56]:
a2.dot(np.arange(3))

array([ 8,  9, 26, 35])

In [58]:
a2.transpose()

array([[ 1,  3,  7, 10],
       [ 2,  3,  8, 11],
       [ 3,  3,  9, 12]])

In [66]:
a2.transpose((0,1))

array([[ 1,  2,  3],
       [ 3,  3,  3],
       [ 7,  8,  9],
       [10, 11, 12]])

In [60]:
np.ones((4,3,2)).transpose((2,1,0)).shape

(2, 3, 4)

`sum()` returns the sum of all the items of an iterable

`cumsum()` Return the cumulative sum of the elements along a given axis.

`cumprod()` Return the cumulative product of elements along a given axis.

In [61]:
print(a2.sum())
print(a2.cumsum())
print(a2.cumprod())

72
[ 1  3  6  9 12 15 22 30 39 49 60 72]
[        1         2         6        18        54       162      1134
      9072     81648    816480   8981280 107775360]


## Numpy ndarrays vs. Matrix

In [62]:
a3 = np.mat(a2)
a3

matrix([[ 1,  2,  3],
        [ 3,  3,  3],
        [ 7,  8,  9],
        [10, 11, 12]])

In [63]:
a3.T

matrix([[ 1,  3,  7, 10],
        [ 2,  3,  8, 11],
        [ 3,  3,  9, 12]])

In [64]:
a3.T*a3

matrix([[159, 177, 195],
        [177, 198, 219],
        [195, 219, 243]])

#### Quick exercise

En una granja tenemos x cerdos, y pollos, solo sabemos que tenemos 8 patas y 3 cabezas.
Cuantos cerdos y pollos tenemos.

A x = b

Solve x

In [65]:
A = np.mat(np.array([[4,2],[1,1]]))
b = np.mat(np.array([8,3])).T
A

matrix([[4, 2],
        [1, 1]])

In [66]:
b

matrix([[8],
        [3]])

In [67]:
A.I*b

matrix([[1.],
        [2.]])

In [68]:
a3[:2,:2]

matrix([[1, 2],
        [3, 3]])

In [69]:
a3[:2,:2].I

matrix([[-1.        ,  0.66666667],
        [ 1.        , -0.33333333]])

In [70]:
a3[:2,:2].I*a3[:2,:2]

matrix([[1., 0.],
        [0., 1.]])

# Linear Algebra

In [71]:
from numpy import linalg as la

In [72]:
help(la)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    Core Linear Algebra Tools
    -------------------------
    Linear algebra basics:
    
    - norm            Vector or matrix norm
    - inv             Inverse of a square matrix
    - solve           Solve a linear system of equations
    - det             Determinant of a square matrix
    - lstsq           Solve linear least-squares problem
    - pinv            Pseudo-inverse (Moore-Penrose) calculated using a singular
                      value decomposition
    - matrix_power    Integer power of a square matrix
    
    Eigenvalues and decompositions:
    
    - eig             Eigenvalues and vectors of a square matrix
    - eigh            Eigenvalues and eigenvectors of a Hermitian matrix
    - eigvals         Eigenvalues of a square matrix
    - eigvalsh        Eigenvalues of a Hermitian matrix
    - qr              QR decomposition of a matrix
    - svd             Singular value decomposition 

### Trace, determinant and inverse

In [73]:
np.trace(np.eye(3))

3.0

In [74]:
print(a2)
print(np.trace(a2))
print(np.trace(a2,offset=1))
print(np.trace(a2,offset=-1))

[[ 1  2  3]
 [ 3  3  3]
 [ 7  8  9]
 [10 11 12]]
13
5
23


In [75]:
a = np.array([[1, 2], [3, 4]])
print(a)
print(a.shape)
np.linalg.det(a)

[[1 2]
 [3 4]]
(2, 2)


-2.0000000000000004

In [76]:
a = np.array([ [[1, 2], [3, 4]], [[1, 2], [2, 1]], [[1, 3], [3, 1]] ])
a

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [2, 1]],

       [[1, 3],
        [3, 1]]])

In [79]:
print(a.shape)
print(la.det(a))

(3, 2, 2)
[-2. -3. -8.]


In [80]:
la.inv(np.array([[1,2],[3,4]]))

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [81]:
la.inv(np.array([[1,2],[3,4]])).dot(np.array([[1,2],[3,4]]))

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

### Norm of a vector and a matrix

In [83]:
a = np.array([[1, 2], [3, 4]])
help(la.norm)

Help on function norm in module numpy.linalg.linalg:

norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.
    
    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D.
    ord : {non-zero int, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object.
    axis : {int, 2-tuple of ints, None}, optional
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix norms of these matrices
        are computed.  If `axis` is None then either a vector norm (when `x`
        is 1-D) or a matrix norm (when `x` is

In [86]:
print(a)
print (la.norm(a))
print (la.norm(a,2))
print (la.norm(a,'fro'))
print (la.norm(a.reshape(4),2))
print (la.norm(a,1))
print (la.norm(a,np.inf))

[[1 2]
 [3 4]]
5.477225575051661
5.464985704219043
5.477225575051661
5.477225575051661
6.0
7.0


In [88]:
b = np.arange(1,4)
print(b)
print(la.norm(b))
print(la.norm(b,2))
print(la.norm(b,1))
print(la.norm(b,np.inf))

[1 2 3]
3.7416573867739413
3.7416573867739413
6.0
3.0


### Matrix factorization: eigen-decomposition y SVD

In [89]:
A = np.matrix(np.array([[3,0],[0,3]]))
A

matrix([[3, 0],
        [0, 3]])

In [90]:
v = np.matrix(np.array([0,1])).T

In [91]:
A*v

matrix([[0],
        [3]])

In [92]:
3*v

matrix([[0],
        [3]])

In [94]:
eigval = la.eigvals(a)
eigval

array([-0.37228132,  5.37228132])

In [95]:
eigvec = la.eig(a)[1]
eigvec

array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]])

In [97]:
u, d,v = la.svd(a)
print(u)
print(d)
print(v)

[[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
[5.4649857  0.36596619]
[[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]


In [98]:
u.dot(np.diag(d)).dot(v)

array([[1., 2.],
       [3., 4.]])

In [99]:
b = np.array([b,b])
b

array([[1, 2, 3],
       [1, 2, 3]])

In [102]:
u,d,v=la.svd(b)
print(u)
print(d)
print(v)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[5.29150262e+00 3.51083347e-16]
[[-0.26726124 -0.53452248 -0.80178373]
 [-0.95618289  0.04390192  0.28945968]
 [ 0.11952286 -0.84401323  0.52283453]]


In [103]:
u,d,v=la.svd(b,full_matrices=0)
print(u)
print(d)
print(v)

[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[5.29150262e+00 3.51083347e-16]
[[-0.26726124 -0.53452248 -0.80178373]
 [-0.95618289  0.04390192  0.28945968]]


In [105]:
u,d,v = la.svd(np.random.rand(1000,4))
u2,d2,v2 = la.svd(np.random.rand(1000,4),full_matrices=0)
print(u.shape,d.size,v.shape)
print(u2.shape,d2.size,v2.shape)

(1000, 1000) 4 (4, 4)
(1000, 4) 4 (4, 4)


### Exectution times comparison vs Python

In [106]:
import time
size_of_vec = 1000
def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1
def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1

In [107]:
t1 = pure_python_version()
t2 = numpy_version()
print(t1/t2)

7.129251700680272
